## Assignment1: Geocoding points of interest

The aim of this exercise is to find out how many people live in proximity to shopping centers in Stockholm.

---

### a) Create a file with the addresses of a few shopping centers in Stockholm

Find out the addresses of shopping centers in Stockholm  and collect them in a text file called `shopping_centres.txt`. The list does not have to be exhaustive - between 5-10 centers would be enough.

 
The text file should be in semicolon-separated format (`;`) and include the following columns:

- `id` (integer) a unique identifier for each shopping centre (a
- `name` (string) of each shopping center
- `addr` (string) the address 


---

### b) Import the file

Read the list of addresses you just prepared into a `pandas.DataFrame` called `shopping_centres`

In [55]:
import pandas as pd
import geopandas as gpd 
import pathlib

NOTEBOOK_PATH = pathlib.Path().resolve()
shopping_centres = pd.read_csv(
    NOTEBOOK_PATH /  "shopping_centres.txt",
    sep=";"
)

shopping_centres

,id,name,addr,Unnamed: 3
0,1,Westfield Mall of Scandinavia,"Stjärntorget 2, 169 79 Solna",NaN
1,2,MOOD STOCKHOLM,"Regeringsgatan 48, 111 44 Stockholm",NaN
2,3,Gallerian,"Hamngatan 37, 111 53 Stockholm",NaN
3,4,Hötorgspassagen,"Drottninggatan 60, 111 21 Stockholm",NaN
4,5,Sturegallerian,"Sturegatan 4, 114 35 Stockholm",NaN
5,6,Liljeholmstorget Galleria,"Nybohovsbacken 38, 117 61 Stockholm",NaN
6,7,Skrapan,"Götgatan 78, 118 30 Stockholm",NaN


---

### c) Geocode the addresses

Geocode the addresses using the Nominatim geocoding service. Join the results with the input data, and store them in a `geopandas.GeoDataFrame` with the same name (`shopping_centres`). 

Remember to define a custom `user_agent` string!

In [56]:
# Geocode addresses

# A Trim leading/trailing spaces in column names
shopping_centres.columns = shopping_centres.columns.str.strip()

# B Use the pandas dataframe from A to geocode.
geocoded_address= gpd.tools.geocode(
    shopping_centres["addr"],
    provider="nominatim",
    user_agent="muffinpython",
    timeout=10
)

# Joining A and B
geocoded_address = geocoded_address.join(shopping_centres)
geocoded_address

,geometry,address,id,name,addr,Unnamed: 3
0,POINT (18.00301 59.37044),"Westfield Mall of Scandinavia, 2, Stjärntorget...",1,Westfield Mall of Scandinavia,"Stjärntorget 2, 169 79 Solna",NaN
1,POINT (18.06796 59.3344),"48, Regeringsgatan, Klara, Norrmalm, Norra inn...",2,MOOD STOCKHOLM,"Regeringsgatan 48, 111 44 Stockholm",NaN
2,POINT (18.06716 59.33245),"37, Hamngatan, Klara, Norrmalm, Norra innersta...",3,Gallerian,"Hamngatan 37, 111 53 Stockholm",NaN
3,POINT (18.06146 59.33383),"Drottninggatan, Klara, Norrmalm, Norra innerst...",4,Hötorgspassagen,"Drottninggatan 60, 111 21 Stockholm",NaN
4,POINT (18.07337 59.33652),"4, Sturegatan, Villastaden, Östermalm, Norra i...",5,Sturegallerian,"Sturegatan 4, 114 35 Stockholm",NaN
5,POINT (18.02233 59.30932),"38, Nybohovsbacken, Nybohov, Liljeholmen, Häge...",6,Liljeholmstorget Galleria,"Nybohovsbacken 38, 117 61 Stockholm",NaN
6,POINT (18.074 59.31203),"78, Götgatan, Skanstull, Södermalm, Södermalms...",7,Skrapan,"Götgatan 78, 118 30 Stockholm",NaN

 reproject the layer into SWEREF99:

In [57]:
# Change Proejction
geocoded_address = geocoded_address.to_crs("EPSG:3006")
geocoded_address

,geometry,address,id,name,addr,Unnamed: 3
0,POINT (670635.567 6585150.741),"Westfield Mall of Scandinavia, 2, Stjärntorget...",1,Westfield Mall of Scandinavia,"Stjärntorget 2, 169 79 Solna",NaN
1,POINT (674509.029 6581308.9),"48, Regeringsgatan, Klara, Norrmalm, Norra inn...",2,MOOD STOCKHOLM,"Regeringsgatan 48, 111 44 Stockholm",NaN
2,POINT (674473.725 6581089.637),"37, Hamngatan, Klara, Norrmalm, Norra innersta...",3,Gallerian,"Hamngatan 37, 111 53 Stockholm",NaN
3,POINT (674142.532 6581228.739),"Drottninggatan, Klara, Norrmalm, Norra innerst...",4,Hötorgspassagen,"Drottninggatan 60, 111 21 Stockholm",NaN
4,POINT (674806.152 6581558.512),"4, Sturegatan, Villastaden, Östermalm, Norra i...",5,Sturegallerian,"Sturegatan 4, 114 35 Stockholm",NaN
5,POINT (672041.636 6578398.913),"38, Nybohovsbacken, Nybohov, Liljeholmen, Häge...",6,Liljeholmstorget Galleria,"Nybohovsbacken 38, 117 61 Stockholm",NaN
6,POINT (674967.96 6578835.611),"78, Götgatan, Skanstull, Södermalm, Södermalms...",7,Skrapan,"Götgatan 78, 118 30 Stockholm",NaN


---

### d) Save the results in a geographical format (such as .shp or .gpkg)

Save `shopping_centres` as a *GeoPackage* named `shopping_centres.gpkg`:

In [58]:
geocoded_address.to_file("shopping_centres.gpkg", driver='GPKG')